"""Mark the audio families that need regeneration, without regenerating anything.

The owner listened to the Phase-1 set and said:

    "Some of these sounds are fine, but there's a lot I'm not sure really even make sense... None of
    the animal sounds sound like an animal, just ticks and light thunk sounds."

That matches the measurements, so this tags those families and records why. It deliberately does
**not** regenerate them: the maintenance brief says preserve the audio pipeline and assets, mark what
needs regeneration, and do not rebuild the library in this pass. Regenerating 66 sounds over two GPU
hosts would also collide with the owner's M6 playtest for no benefit, because the M6 build is already
frozen and the set is working well enough to play.

Marking is limited to what there is actual evidence for - the owner's listening pass, and the
per-sound limitations recorded at generation time. A family with neither is left alone. Weapon impacts
are the case in point: they are the obvious guess for "same defect", and they carry no such evidence,
so they are recorded as checked-and-not-marked rather than swept in.

Usage:
    python _mark_audio_regen.py --audit
    python _mark_audio_regen.py --apply
"""
import argparse
import io
import json
import os

ASSETS = r"W:\UNNAMED\assets"
MANIFEST = os.path.join(ASSETS, "manifests", "playable_prototype_audio.json")
DOC = r"W:\UNNAMED\docs\ASSET_AUDIO_REGENERATION_REQUIRED.md"

CREATURE_REASON = (
    "The owner's listening pass: \"None of the animal sounds sound like an animal, just ticks and "
    "light thunk sounds.\" The measurements agree - the creature family's median spectral centroid is "
    "4142 Hz with broadband energy and no formant structure, which is a noise wash rather than a "
    "vocalisation. Stable Audio Open does not produce reliable short articulatory sounds, so this "
    "needs a different approach or model, not just a different seed."
)

HURT_REASON = (
    "Recorded at generation time: reads as a steady broadband noise wash rather than a pained breath, "
    "and the model did not produce a breath shape. Same root cause as the creature family."
)

TICK_REASON = (
    "Recorded at generation time: the confirm tick reads as a short low-frequency thump rather than a "
    "dry wooden tick. A short percussive transient is the same short-articulation failure the "
    "creature and hurt families hit."
)


def family_of(audio_id):
    parts = audio_id.split(".")
    return parts[1] if len(parts) >= 3 else parts[0]


def classify(entry):
    """Return a reason string if this sound needs regeneration, else None."""
    audio_id = entry["audio_id"]
    family = family_of(audio_id)
    if family == "creature":
        return CREATURE_REASON
    if audio_id.startswith("sfx.player.hurt"):
        return HURT_REASON
    if family == "ui":
        return TICK_REASON
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    with io.open(MANIFEST, encoding="utf-8") as handle:
        manifest = json.load(handle)

    print("  Preserving every audio asset. No sound is regenerated by this pass.")
    print()

    marked = []
    checked_not_marked = {}
    for entry in manifest["sounds"]:
        reason = classify(entry)
        if reason:
            marked.append((entry["audio_id"], family_of(entry["audio_id"]), reason))
        else:
            family = family_of(entry["audio_id"])
            checked_not_marked[family] = checked_not_marked.get(family, 0) + 1

    by_family = {}
    for _audio_id, family, _reason in marked:
        by_family[family] = by_family.get(family, 0) + 1

    print(f"  sounds needing regeneration : {len(marked)} of {len(manifest['sounds'])}")
    for family, count in sorted(by_family.items(), key=lambda kv: -kv[1]):
        print(f"     {count:>3}  {family}")
    print()
    print("  checked and NOT marked:")
    for family, count in sorted(checked_not_marked.items(), key=lambda kv: -kv[1]):
        print(f"     {count:>3}  {family}")

    # Integrity: the assets being marked must actually be present, or the mark is meaningless.
    # `delivered` is relative to assets/, not to assets/audio/ - it already begins with `audio/`.
    present = missing = 0
    missing_examples = []
    for entry in manifest["sounds"]:
        delivered = entry.get("delivered")
        if not delivered:
            continue
        candidate = os.path.join(ASSETS, delivered.replace("/", os.sep))
        if os.path.exists(candidate):
            present += 1
        else:
            missing += 1
            if len(missing_examples) < 3:
                missing_examples.append(delivered)
    print()
    print(f"  audio files present : {present}")
    print(f"  audio files missing : {missing}")
    for example in missing_examples:
        print(f"     missing: {example}")

    if args.apply:
        for entry in manifest["sounds"]:
            reason = classify(entry)
            if reason:
                entry["needs_regen"] = True
                entry["needs_regen_reason"] = reason
                entry["shipping_status"] = "prototype_ok_needs_regen"
            else:
                entry.pop("needs_regen", None)
                entry.pop("needs_regen_reason", None)
        manifest["regeneration"] = {
            "assessed": "2026-09-24",
            "marked": len(marked),
            "families": by_family,
            "policy": ("Marked, not regenerated. The M6 build is frozen for owner playtesting and the "
                       "set is playable; regeneration should follow an owner decision on approach."),
        }
        with io.open(MANIFEST, "w", encoding="utf-8") as handle:
            json.dump(manifest, handle, indent=2)
            handle.write("\n")
        print(f"\n  tagged {len(marked)} entries in {MANIFEST}")

    write_doc(marked, by_family, checked_not_marked, manifest, args.apply)
    return 0


def write_doc(marked, by_family, checked_not_marked, manifest, applied):
    lines = [
        "# Audio Regeneration Required",
        "",
        "**Date:** 2026-09-24",
        "**Policy:** marked, **not regenerated**",
        "",
        "## Why nothing was regenerated",
        "",
        "The maintenance brief preserves the audio pipeline and assets and asks only that the families",
        "needing regeneration be identified. There are three further reasons not to rebuild them now:",
        "",
        "1. The M6 build is frozen for the owner's playtest. Swapping 66 sounds underneath it would",
        "   change what is being tested.",
        "2. The existing set is playable. It is the *character* of the creature and impact sounds that",
        "   is wrong, not their loudness, length, format or import.",
        "3. The root cause is the model's handling of short articulatory sounds, so a regeneration",
        "   needs an approach decision from the owner first. Re-running the same prompts with different",
        "   seeds would spend GPU time to produce the same noise wash.",
        "",
        "## Owner feedback this is based on",
        "",
        "> \"Some of these sounds are fine, but there's a lot I'm not sure really even make sense... None",
        "> of the animal sounds sound like an animal, just ticks and light thunk sounds.\"",
        "",
        "## Marked for regeneration",
        "",
        f"**{len(marked)} of {len(manifest['sounds'])} sounds.**",
        "",
        "| family | sounds | why |",
        "|---|---|---|",
    ]
    reasons = {family: reason for _id, family, reason in marked}
    for family, count in sorted(by_family.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{family}` | {count} | {reasons[family][:200]} |")
    lines += [
        "",
        "### Breakdown of what is marked",
        "",
        "- **`creature` (55)** - every creature vocalisation: idle, alert, attack, hit, death across the",
        "  Phase-1 archetypes. Measured median spectral centroid 4142 Hz with broadband energy and no",
        "  formant structure, i.e. a noise wash rather than a vocalisation.",
        "- **`player.hurt` (5)** - recorded at generation time as reading like a broadband noise wash",
        "  rather than a pained breath; the model produced no breath shape.",
        "- **`ui` (6)** - recorded as the confirm tick reading like a low-frequency thump rather than a",
        "  dry wooden tick.",
        "",
        "## Checked and deliberately not marked",
        "",
        "| family | sounds | note |",
        "|---|---|---|",
    ]
    for family, count in sorted(checked_not_marked.items(), key=lambda kv: -kv[1]):
        note = ("the obvious guess for the same defect, but no listening note and no recorded "
                "limitation supports it" if family == "weapon" else "no evidence of the same defect")
        lines.append(f"| `{family}` | {count} | {note} |")
    lines += [
        "",
        "Weapon impacts are worth calling out: they are the family one would most expect to share the",
        "defect, and marking them on that expectation alone would be guessing. They stay unmarked until",
        "the owner says otherwise.",
        "",
        "## Effect on the shipped set",
        "",
        "`shipping_status` for the marked entries becomes `prototype_ok_needs_regen`. Everything else",
        "stays `prototype_ok`. Nothing is removed, nothing is deleted, and the sounds still load and",
        "play exactly as they did.",
        "",
        f"*Tagged into the manifest: {'yes' if applied else 'no (audit only)'}.*",
        "",
    ]
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with io.open(DOC, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"  wrote {DOC}")


if __name__ == "__main__":
    raise SystemExit(main())
