<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>UNNAMED.Application</RootNamespace>
    <AssemblyName>UNNAMED.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\EntityRegistry\EntityRegistry.csproj" />
    <ProjectReference Include="..\World\World.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\Content\Content.csproj" />
  </ItemGroup>

</Project>